import { RoleScope } from '../generated/prisma/enums';
import {
  DEFAULT_PERMISSION_KEYS,
  type DefaultPermissionKey,
} from './default-permissions';

export interface DefaultRoleDefinition {
  readonly key: string;
  readonly name: string;
  readonly description: string;
  readonly scope: RoleScope;
  readonly isAssignable: boolean;
  readonly permissions: readonly DefaultPermissionKey[];
}

export const DEFAULT_ROLES = [
  {
    key: 'organisation_owner',
    name: 'Organisation Owner',
    description:
      'Full organisation-level authority, including sensitive administrative operations.',
    scope: RoleScope.ORGANISATION,
    isAssignable: false,
    permissions: DEFAULT_PERMISSION_KEYS,
  },
  {
    key: 'system_administrator',
    name: 'System Administrator',
    description:
      'Administers organisation systems, users, access and operational configuration.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: DEFAULT_PERMISSION_KEYS,
  },
  {
    key: 'compliance_manager',
    name: 'Compliance Manager',
    description:
      'Reviews organisation activity for compliance, risk, document assurance and governance.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'members.read',
      'enquiries.read',
      'enquiries.read_all',
      'enquiries.update',
      'enquiries.close',
      'workforce.read',
      'job_profiles.read',
      'kpis.read',
      'agent_profiles.read',
      'clients.read',
      'clients.read_all',
      'matters.read',
      'matters.read_all',
      'matters.update_all',
      'matters.status.manage',
      'matters.compliance.manage',
      'tasks.read',
      'deadlines.read',
      'deadlines.manage',
      'documents.read',
      'documents.restricted.read',
      'documents.privileged.read',
      'documents.archive',
      'document_requests.read',
      'document_requests.manage',
      'matter_timeline.read',
      'automation.read',
      'sla.read',
      'sla.manage',
      'approvals.read',
      'approvals.decide',
      'escalations.read',
      'communications.read',
      'communications.delivery.read',
      'communication_templates.read',
      'portal_access.read',
      'finance.read',
      'ledger.read',
      'integrations.read',
      'command_centre.read',
    ],
  },
  {
    key: 'solicitor',
    name: 'Solicitor',
    description:
      'Manages assigned enquiries, clients, matters, deadlines and privileged legal documents.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'enquiries.create',
      'enquiries.read',
      'enquiries.update',
      'enquiries.convert',
      'enquiries.close',
      'clients.create',
      'clients.read',
      'clients.update',
      'matters.create',
      'matters.read',
      'matters.update',
      'matters.status.manage',
      'matters.compliance.manage',
      'matters.parties.manage',
      'tasks.read',
      'tasks.create',
      'tasks.update',
      'tasks.assign',
      'tasks.complete',
      'deadlines.read',
      'deadlines.create',
      'deadlines.update',
      'deadlines.assign',
      'deadlines.manage',
      'documents.read',
      'documents.upload',
      'documents.classification.manage',
      'documents.restricted.read',
      'documents.privileged.read',
      'documents.archive',
      'document_requests.read',
      'document_requests.create',
      'document_requests.send',
      'document_requests.manage',
      'matter_timeline.read',
      'automation.read',
      'work_items.complete',
      'sla.read',
      'approvals.read',
      'approvals.request',
      'approvals.decide',
      'escalations.read',
      'communications.read',
      'communications.send',
      'communications.manage',
      'communications.delivery.read',
      'communication_templates.read',
      'communication_reminders.manage',
      'portal_access.read',
      'portal_access.manage',
      'portal_updates.publish',
      'finance.read',
      'invoices.create',
      'command_centre.read',
    ],
  },
  {
    key: 'sales_manager',
    name: 'Sales Manager',
    description:
      'Manages the organisation enquiry pipeline and authorised sales team.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'members.read',
      'enquiries.create',
      'enquiries.read',
      'enquiries.read_all',
      'enquiries.update',
      'enquiries.assign',
      'enquiries.convert',
      'enquiries.close',
      'clients.create',
      'clients.read',
      'clients.read_all',
      'clients.update',
      'clients.update_all',
      'matters.create',
      'matters.read',
      'matters.read_all',
      'matters.update',
      'matters.update_all',
      'matters.assign',
      'matters.status.manage',
      'matters.parties.manage',
      'automation.read',
      'automation.manage',
      'work_items.complete',
      'sla.read',
      'sla.manage',
      'approvals.read',
      'approvals.request',
      'approvals.decide',
      'escalations.read',
      'communications.read',
      'communications.send',
      'communications.manage',
      'communication_templates.read',
      'integrations.read',
      'command_centre.read',
    ],
  },
  {
    key: 'sales_agent',
    name: 'Sales Agent',
    description:
      'Creates and manages enquiries within the authorised individual scope.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'enquiries.create',
      'enquiries.read',
      'enquiries.update',
      'enquiries.convert',
      'enquiries.close',
      'clients.create',
      'clients.read',
      'clients.update',
      'matters.create',
      'matters.read',
      'matters.update',
      'matters.status.manage',
      'matters.parties.manage',
      'automation.read',
      'work_items.complete',
      'sla.read',
      'approvals.read',
      'approvals.request',
      'escalations.read',
      'communications.read',
      'communications.send',
      'communication_templates.read',
    ],
  },
  {
    key: 'finance',
    name: 'Finance',
    description:
      'Runs controlled billing, payment allocation and accounting evidence for the organisation.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'enquiries.read_all',
      'clients.read',
      'clients.read_all',
      'matters.read',
      'matters.read_all',
      'finance.read',
      'finance.settings.manage',
      'invoices.create',
      'invoices.issue',
      'invoices.void',
      'payments.record',
      'payments.refund',
      'ledger.read',
      'integrations.read',
      'command_centre.read',
    ],
  },
  {
    key: 'read_only',
    name: 'Read Only',
    description:
      'Provides read-only access to authorised business and case-operation information.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'enquiries.read_all',
      'clients.read',
      'clients.read_all',
      'matters.read',
      'matters.read_all',
      'tasks.read',
      'deadlines.read',
      'matter_timeline.read',
      'automation.read',
      'sla.read',
      'approvals.read',
      'escalations.read',
      'communications.read',
      'communication_templates.read',
      'portal_access.read',
      'finance.read',
      'ledger.read',
    ],
  },
  {
    key: 'case_manager',
    name: 'Case Manager',
    description:
      'Supervises client onboarding, matter allocation, tasks, deadlines, documents and compliance.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'members.read',
      'enquiries.read',
      'enquiries.read_all',
      'enquiries.update',
      'enquiries.convert',
      'clients.create',
      'clients.read',
      'clients.read_all',
      'clients.update',
      'clients.update_all',
      'clients.archive',
      'matters.create',
      'matters.read',
      'matters.read_all',
      'matters.update',
      'matters.update_all',
      'matters.assign',
      'matters.status.manage',
      'matters.compliance.manage',
      'matters.parties.manage',
      'matters.archive',
      'tasks.read',
      'tasks.create',
      'tasks.update',
      'tasks.assign',
      'tasks.complete',
      'deadlines.read',
      'deadlines.create',
      'deadlines.update',
      'deadlines.assign',
      'deadlines.manage',
      'documents.read',
      'documents.upload',
      'documents.classification.manage',
      'documents.restricted.read',
      'documents.archive',
      'document_requests.read',
      'document_requests.create',
      'document_requests.send',
      'document_requests.manage',
      'matter_timeline.read',
      'automation.read',
      'automation.manage',
      'work_items.complete',
      'sla.read',
      'sla.manage',
      'approvals.read',
      'approvals.request',
      'approvals.decide',
      'escalations.read',
      'communications.read',
      'communications.send',
      'communications.manage',
      'communications.delivery.read',
      'communication_templates.read',
      'communication_templates.manage',
      'communication_reminders.manage',
      'portal_access.read',
      'portal_access.manage',
      'portal_updates.publish',
      'finance.read',
      'invoices.create',
      'integrations.read',
      'command_centre.read',
    ],
  },
  {
    key: 'case_worker',
    name: 'Case Worker',
    description:
      'Manages assigned clients, tasks, deadlines and documents under controlled supervision.',
    scope: RoleScope.ORGANISATION,
    isAssignable: true,
    permissions: [
      'organisation.read',
      'enquiries.read',
      'enquiries.update',
      'enquiries.convert',
      'clients.create',
      'clients.read',
      'clients.update',
      'matters.create',
      'matters.read',
      'matters.update',
      'matters.status.manage',
      'matters.compliance.manage',
      'matters.parties.manage',
      'tasks.read',
      'tasks.create',
      'tasks.update',
      'tasks.complete',
      'deadlines.read',
      'deadlines.create',
      'deadlines.update',
      'documents.read',
      'documents.upload',
      'document_requests.read',
      'document_requests.create',
      'document_requests.send',
      'matter_timeline.read',
      'automation.read',
      'work_items.complete',
      'sla.read',
      'approvals.read',
      'approvals.request',
      'escalations.read',
      'communications.read',
      'communications.send',
      'communication_templates.read',
      'portal_access.read',
      'portal_updates.publish',
    ],
  },
] as const satisfies readonly DefaultRoleDefinition[];
