-- Canonical Enquiries permissions.
-- Idempotent: existing permission keys are updated, not duplicated.

INSERT INTO public.permissions (
  id,
  key,
  name,
  description,
  resource,
  action,
  data_scope,
  is_sensitive,
  requires_mfa,
  allows_ai_use,
  is_active,
  metadata,
  created_at,
  updated_at
)
VALUES
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.create',
    'Create enquiries',
    'Create enquiries within an authorised organisation.',
    'enquiries',
    'create',
    NULL,
    false,
    false,
    false,
    true,
    '{"classification":"business-confidential"}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  ),
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.read',
    'Read assigned enquiries',
    'Read enquiries assigned to or created by the authorised user.',
    'enquiries',
    'read',
    NULL,
    false,
    false,
    false,
    true,
    '{"classification":"business-confidential"}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  ),
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.read_all',
    'Read all organisation enquiries',
    'Read all non-deleted enquiries within an authorised organisation.',
    'enquiries',
    'read_all',
    NULL,
    true,
    false,
    false,
    true,
    '{"classification":"business-confidential"}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  ),
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.update',
    'Update enquiries',
    'Update enquiries within the user’s authorised scope.',
    'enquiries',
    'update',
    NULL,
    false,
    false,
    false,
    true,
    '{"classification":"business-confidential"}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  ),
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.assign',
    'Assign enquiries',
    'Assign or reassign enquiries to authorised organisation users.',
    'enquiries',
    'assign',
    NULL,
    true,
    false,
    false,
    true,
    '{"classification":"business-confidential"}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  ),
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.convert',
    'Convert enquiries',
    'Convert qualified enquiries into clients or cases.',
    'enquiries',
    'convert',
    NULL,
    true,
    false,
    false,
    true,
    '{"classification":"business-confidential"}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  ),
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.close',
    'Close enquiries',
    'Close enquiries within an authorised organisation.',
    'enquiries',
    'close',
    NULL,
    true,
    false,
    false,
    true,
    '{"classification":"business-confidential"}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  ),
  (
    pg_catalog.gen_random_uuid(),
    'enquiries.delete',
    'Delete enquiries',
    'Delete enquiries where explicitly authorised.',
    'enquiries',
    'delete',
    NULL,
    true,
    false,
    false,
    true,
    '{"classification":"business-confidential","high_risk":true}'::jsonb,
    pg_catalog.now(),
    pg_catalog.now()
  )
ON CONFLICT (key) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  resource = EXCLUDED.resource,
  action = EXCLUDED.action,
  is_sensitive = EXCLUDED.is_sensitive,
  requires_mfa = EXCLUDED.requires_mfa,
  allows_ai_use = EXCLUDED.allows_ai_use,
  is_active = true,
  metadata = EXCLUDED.metadata,
  deleted_at = NULL,
  updated_at = pg_catalog.now();